### ISSUE TITLE
networkx dependency on unknown version v2.2.8

### ISSUE THREAD

**Issue by jmillikin** [LukeSerne/DecompVis#2]
Hello,

The current `requirements.txt` specifies a dependency `networkx==2.2.8`. I can't find this version listed in either PyPI[0] or the networkx homepage[1]. Was this a typo, or is there a non-default location I should be downloading dependencies from?

[0] https://pypi.org/project/networkx/#history
[1] https://networkx.org/

**Comment by LukeSerne** [comment]
Hey, I think that was a typo (of `2.8.8` probably). Either way, using `networkx 3.1` (the latest version at the time of writing) works just fine as well, so I'll update the `requirements.txt` to list the correct version and make the version requirement less strict. Thanks a lot for creating this issue - I don't usually keep an eye on `requirements.txt`...
